language: node_js
node_js:
    - "node"
sudo: false
cache:
  directories:
    - $(npm config get cache)
install:
    - npm config set prefer-offline true
    - npm install

script:
    - npm run lint
