dist: focal
language: node_js
node_js:
    - node
sudo: false
install:
    - npm config set prefer-offline false
    - npm install

script:
    - npm run lint -- --report-unused-disable-directives --max-warnings 0
